#!/usr/bin/env ruby
# Copyright 2016 Nyk Ma <moe@nayuki.info>
# Licensed under the terms of the MIT license.
#
# This script outputs current battery status, and should be used with
# i3blocks.
#
# Use FontAwesome to show eye-candy icons properly.
# https://fortawesome.github.io/Font-Awesome/cheatsheet/

# $ acpi -b
# Battery 0: Full, 98%

charge_status, percentage, = `acpi -b`.gsub(/Battery 0: /, '').split(', ')
percentage = percentage.gsub(/\%/, '').to_i
full_text = ''

case charge_status
when 'Discharging' then full_text += ''
when 'Charging' then full_text += ' '
when 'Full' then full_text += ' '
end

case percentage
when 0..5
  full_text += ''
  color = '#FF0000'
when 5..25
  full_text += ''
  color = '#FFAE00'
when 25..50
  full_text += ''
  color = '#FFF600'
when 50..75
  full_text += ''
  color = '#A8FF00'
when 75..100
  full_text += ''
  color = '#00FF00'
end

full_text += " #{percentage}%"

2.times { puts full_text }
puts color

exit
