#!/usr/bin/env ruby
# Copyright 2016 Nyk Ma <moe@nayuki.info>
# Licensed under the terms of the MIT license.
#
# This script outputs current weather based on city pinyin in China,
# and should be used with i3blocks.
#
# Help yourself by editing `CITY_ID`
#
# Use FontAwesome to show eye-candy icons properly.
# https://fortawesome.github.io/Font-Awesome/cheatsheet/

# require 'byebug'

# Find city ID in http://bulk.openweathermap.org/sample/city.list.json.gz
CITY_ID = '1796236' # Shanghai
APP_ID ='xxxxx'
UNIT = :metric # :imperial

require 'json'
require 'uri'
require 'net/http'

uri = URI.parse("http://api.openweathermap.org")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Get.new("/data/2.5/weather?id=#{CITY_ID}&appid=#{APP_ID}&units=#{UNIT}")
response = http.request(request)

result = JSON.parse(response.body)
abort if result['cod'] != 200
full_text = case result['weather'].first['main']
            when 'Clouds' then '☁️'
            when 'Clear' then '☀️'
            else result['weather'].first['main']
            end
full_text += " #{result['main']['temp'].to_i}°C"
text_color = case result['main']['temp'].to_i
             when -10..0 then '#0080FF'
             when  0..10 then '#4DA6FF'
             when 10..20 then '#4DFFA5'
             when 20..25 then '#FFB1B1'
             when 25..30 then '#FF6262'
             when 30..40 then '#FF1414'
             else '#FFFFFF'
             end

puts full_text, full_text, text_color

__END__
{"errNum"=>0,
 "errMsg"=>"success",
 "retData"=>
{"city"=>"上海",
 "pinyin"=>"shanghai",
 "citycode"=>"101020100",
 "date"=>"16-03-26",
 "time"=>"11:00",
 "postCode"=>"200000",
 "longitude"=>121.445,
 "latitude"=>31.213,
 "altitude"=>"19",
 "weather"=>"多云",
 "temp"=>"15",
 "l_tmp"=>"8",
 "h_tmp"=>"15",
 "WD"=>"西风",
 "WS"=>"微风(<10km/h)",
 "sunrise"=>"05:49",
 "sunset"=>"18:09"
}
}
